### ISSUE TITLE
Pipeline doesn't run when created

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#10]
When the pipeline is created in continuous-delivery scenario, it first run stalls and doesn't get started. Stoping and restarting the pipeline gets around the issue

**Comment by siamaksade** [comment]
Seem to be fixed in v3.6.173.0.49. Waiting to be verified on Katacoda

**Comment by BenHall** [comment]
When was .49 released? We can rebuild the environment

**Comment by siamaksade** [comment]
Yesterday https://access.redhat.com/errata/RHBA-2017:3049?sc_cid=701600000006NHXAA2

We should fix your subscription as well in this round

**Comment by BenHall** [comment]
Image has been rebuilt as `v3.6.173.0.49`. Running tests now and will deploy over weekend.

**Comment by BenHall** [comment]
This has been rolled out and a new set of environments initialised for testing
