### ISSUE TITLE
Jenkins oauth login fails 

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#11]
Jenkins authentication is integrated with OpenShift but when I try to login, it fails with:

```
{  
   "error":"invalid_request",
   "error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
   "state":"M2M4NTIxNTUtM2VmZC00"
}
```

To produce, deploy Jenkins from the catalog and then open Jenkins route url to login using OpenShift credentials.

**Comment by siamaksade** [comment]
It also occurs on learn.openshift.com scenarios

**Comment by BenHall** [comment]
When you say happens on learn.openshift.com, do you mean if you deploy Jenkins?

Or is this an issue with logging into the OC dashboard?

**Comment by siamaksade** [comment]
I mean if I start a scenario on learn.openshift.com and then deploy Jenkins on it.

**Comment by BenHall** [comment]
Fixed!! 🎉

Because the URL has port 80, I send traffic to port 80 but then Jenkins redirects to HTTPs. Hence the loop. It's a fix of an awkward fix, so we may need to re-visit.

**Comment by siamaksade** [comment]
👍 🍻
