### ISSUE TITLE
Click to execute command opens the OpenShift console

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#13]
Click on the 2nd and 3rd commands, executes the command in the correct terminal but also opens a new browser tab pointing at the OpenShift web console:
https://github.com/openshift-roadshow/cloud-native-katacoda/blob/master/scenarios/debug-app/03-debug.md

<img width="450" alt="screen shot 2017-10-26 at 15 23 20" src="https://user-images.githubusercontent.com/1174934/32055290-a1a15094-ba61-11e7-9cd7-9e78e28bfac5.png">

**Comment by BenHall** [comment]
Ah sorry, it's trying to change the user to the next tab but it doesn't take into account the dashboard tab on the editor view. Fixing now.
