### ISSUE TITLE
Cursor goes to the beginning of the line in 2nd and 3rd terminals

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#14]
When opening a new terminal, the cursor goes back to the beginning of the line midway and overwrites the line

<img width="693" alt="screen shot 2017-10-26 at 15 27 52" src="https://user-images.githubusercontent.com/1174934/32055528-628360ea-ba62-11e7-874a-f2adecd9a060.png">

**Comment by BenHall** [comment]
Thanks! We missed this. When launching a terminal we need to set the rows/cols. We do it on the main one but the changes aren't being applied to the next scenarios.

**Comment by siamaksade** [comment]
@BenHall this issue started to appear again

**Comment by BenHall** [comment]
Fixed, just need to roll out the update.

**Comment by siamaksade** [comment]
This started to appear again
