### ISSUE TITLE
Keep the katacoda logo in the terminal on a dedicated line

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#18]
The katacoda logo in the terminal window overlaps the last line:

<img width="902" alt="screen shot 2017-11-01 at 16 16 14" src="https://user-images.githubusercontent.com/1174934/32281842-47871120-bf20-11e7-8f59-0a9ea2b24b74.png">

If possible, it would be better to add a margin in the bottom and only show the katacoda logo on that line.

**Comment by BenHall** [comment]
Thanks for the suggestion! Done.
