### ISSUE TITLE
Add {{open}} macro to step 3 in Enterprise Microservices with WildFly Swarm

### ISSUE THREAD

**Issue by tqvarnst** [openshift-roadshow/cloud-native-katacoda#19]
In step 3 of the Enterprise Microservices with WildFly Swarm the user is asked to review pom.xml, persistance.xml and project-stages.yml. By using the {{open}} macro users don't have to browse the directory structure to find the files

**Comment by siamaksade** [comment]
Good tip. The styling is confusing though. Needs an update

**Comment by BenHall** [comment]
Suggestions are more than welcome as it was introduced as an experiment to see if it helped scenario flow.

**Comment by BenHall** [comment]
![screenshot 2017-12-12 23 25 42](https://user-images.githubusercontent.com/82614/33913953-c9d06832-df93-11e7-95aa-4f1f773e7dc4.png)

Updated the style a little...
