### ISSUE TITLE
Change landing page styling for scenarios

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#2]
Change the styling for scenarios on the branded site so that 3 line fit as the scenario name. Here is the CSS for that:

```
#course-pathway .panel {
    height: 250px;
}

#course-pathway .panel .content {
    height: 126px;
}
```

Before applying the CSS:
<img width="803" alt="screen shot 2017-10-17 at 11 24 57" src="https://user-images.githubusercontent.com/1174934/31657827-bb1401b8-b32f-11e7-9f84-16168e4234dc.png">

After applying the CSS:
<img width="792" alt="screen shot 2017-10-17 at 11 26 00" src="https://user-images.githubusercontent.com/1174934/31657826-bafba082-b32f-11e7-9cf8-bdcb336193bf.png">

**Comment by BenHall** [comment]
Thanks! This along with the homepage styling will be deployed tomorrow.
