### ISSUE TITLE
Add an admin user to openshift

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#32]
In order to avoid switching between`system:admin` and `developer` and skip the cert issue, add an `admin` user to openshift when Ansible runs, to allow switching between `admin` and `developer` using the long master url:

```
oc create user admin --full-name=admin
oc adm policy add-cluster-role-to-user cluster-admin admin
```

**Comment by siamaksade** [comment]
any updates?

**Comment by BenHall** [comment]
This should be lived and used in the recent training
