### ISSUE TITLE
Lab Reactive Microservices with Eclipse Vert.x  - Step 7 of 9 : Typo

### ISSUE THREAD

**Issue by nboukhed** [openshift-roadshow/cloud-native-katacoda#35]
1- "It’s time to build and deploy Catalog service ...." 
Should be "It’s time to build and deploy API Gateway service ...."

2- Also, "The API Gateway uber-jar is built using WildFly Swarm..."
Should be "The API Gateway uber-jar is built using Vert.x"

**Comment by siamaksade** [comment]
Fixed
