### ISSUE TITLE
Deploy Gogs during cluster initialisation

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#5]

**Comment by BenHall** [comment]
The URL structure will be `gogs-infra-app-[[HOST_SUBDOMAIN]]-80-[[KATACODA_HOST]].environments.katacoda.com`

For example:
http://gogs-infra-app-2886795272-80-kitek01.environments.katacoda.com/

![screenshot 2017-10-23 15 59 21](https://user-images.githubusercontent.com/82614/31896238-291fe354-b80b-11e7-8e52-7d7caa7e85ed.png)
