### ISSUE TITLE
Editor path is ignored in WF Swarm scenario

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#6]
The editor path is set to `/root/inventory-wildfly-swarm`:
https://github.com/openshift-roadshow/cloud-native-katacoda/blob/master/scenarios/microservice-wildfly-swarm/index.json#L44

However, the editor shows `/root`:
<img width="772" alt="screen shot 2017-10-25 at 15 54 30" src="https://user-images.githubusercontent.com/1174934/32002461-e6b9f4f8-b99c-11e7-8a66-5037d9d8c6e1.png">

**Comment by BenHall** [comment]
Sorry, about that @siamaksade. I've added a quick workaround and will look into the longer term fix tomorrow.

**Comment by siamaksade** [comment]
Verified that workaround works 👍  Shall I close the ticket or keep it open for the long-term fix?

**Comment by BenHall** [comment]
Let's keep it open so I don't lose track of it. Will close once live.
