### ISSUE TITLE
File gets created in the root folder

### ISSUE THREAD

**Issue by siamaksade** [openshift-roadshow/cloud-native-katacoda#9]
In the continous-delivery scenario, the Jenkinsfile gets created in the root folder instead of `./inventory-wildfly-swarm`. The path is specified via:

    <pre class="file" data-filename="./inventory-wildfly-swarm/Jenkinsfile" data-target="replace">

https://raw.githubusercontent.com/openshift-roadshow/cloud-native-katacoda/master/scenarios/continuous-delivery/03-define-pipeline.md

**Comment by BenHall** [comment]
Sadly it's the same / related to #6.

Will fix this later today.
